version: '3'

services:
  server:
    build: .
    ports:
      - "4599:4599"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PORT=4599
    depends_on:
      - trains
    networks:
      - app-network
    restart: unless-stopped

  trains:
    build:
      context: .
      dockerfile: ./trains/Dockerfile
    ports:
      - "4600:4600"
    volumes:
      - ./trains:/app
      - ./train_types.py:/app/train_types.py
      - ./requirements.txt:/app/requirements.txt
    environment:
      - PYTHONPATH=/app
      - PORT=4600
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
